apiVersion: v1
kind: Service
metadata:
  name: argocd-sync-to-healthy-exporter
  namespace: exporter
  labels:
    app: sync-to-healthy-exporter
    release: kube-prometheus-stack
spec:
  selector:
    app: sync-to-healthy-exporter
  ports:
  - name: http
    port: 8000
    targetPort: 8000
